name       : zbar
version    : 0.23.1
release    : 13
source     :
    - https://linuxtv.org/downloads/zbar/zbar-0.23.1.tar.gz : c72b19eb63f48781ae5ff1830236f4e753f4bd6418cd781aea1cd85d625b119e
license    : LGPL-2.1-or-later
component  : programming.library
summary    : ZBar is an open source software suite for reading bar codes from various sources, such as video streams, image files and raw intensity sensors
description: |
    ZBar Bar Code Reader is an open source software suite for reading bar codes from various sources, such as video streams, image files and raw intensity sensors. It supports EAN-13/UPC-A, UPC-E, EAN-8, Code 128, Code 39, Codabar, Interleaved 2 of 5 and QR Code.  Included with the library are basic applications for decoding captured bar code images and using a video device (eg, webcam) as a bar code scanner.  For application developers, language bindings are included for C, C++, Python and Perl as well as GUI widgets for Qt, GTK and PyGTK.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(MagickWand)
    - pkgconfig(python3)
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-pkgconfig-for-GTK3.patch
    # Python 3.9
    sed -i '/tp_print/d' python/enum.c
    %configure --with-python=python3 --disable-nls --disable-doc --enable-static=no
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share/doc
    # Move to correct location
    install -dm00644 $installdir/usr/share/dbus-1/system.d
    mv $installdir/etc/dbus-1/system.d/org.linuxtv.Zbar.conf $installdir/usr/share/dbus-1/system.d/
    rm -rf $installdir/etc
